
# Generated by CodiumAI

from homework.ex3_14_01 import count_sentences

import unittest

class TestCountSentences(unittest.TestCase):

    #  Returns 0 when given an empty string.
    def test_empty_string(self):
        text = ""
        result = count_sentences(text)
        self.assertEqual(result, 0)

    #  Returns 1 when given a string with only one sentence.
    def test_one_sentence(self):
        text = "This is a sentence."
        result = count_sentences(text)
        self.assertEqual(result, 1)

    #  Returns the correct number of sentences when given a string with multiple sentences.
    def test_multiple_sentences(self):
        text = "This is the first sentence. This is the second sentence. This is the third sentence."
        result = count_sentences(text)
        self.assertEqual(result, 3)

    #  Returns 1 when given a string with only a period.
    def test_period(self):
        text = "."
        result = count_sentences(text)
        self.assertEqual(result, 1)

    #  Returns 2 when given a string with a period and a question mark.
    def test_period_question_mark(self):
        text = ".?"
        result = count_sentences(text)
        self.assertEqual(result, 2)

    #  Returns 2 when given a string with a period and an exclamation mark.
    def test_period_exclamation_mark(self):
        text = ".!"
        result = count_sentences(text)
        self.assertEqual(result, 2)
