
# Generated by CodiumAI

from homework.ex1_14_01 import is_palindrome

import unittest

class TestIsPalindrome(unittest.TestCase):

    #  Should return True for a single word palindrome
    def test_single_word_palindrome(self):
        result = is_palindrome("level")
        self.assertTrue(result)

    #  Should return True for a multi-word palindrome
    def test_multi_word_palindrome(self):
        result = is_palindrome("A man a plan a canal Panama")
        self.assertTrue(result)

    #  Should return True for a palindrome with mixed case
    def test_mixed_case_palindrome(self):
        result = is_palindrome("Madam Arora teaches malayalam")
        self.assertTrue(result)

    #  Should return False for a string with only punctuation
    def test_punctuation_string(self):
        result = is_palindrome("!@#$%^&*()")
        self.assertFalse(result)

    #  Should return False for a string with only numbers
    def test_number_string(self):
        result = is_palindrome("1234567890")
        self.assertFalse(result)

    #  Should return False for a non-string input
    def test_non_string_input(self):
        result = is_palindrome(12345)
        self.assertFalse(result)
