
# Generated by CodiumAI

from homework.ex4_14_01 import process_text

import unittest

class TestProcessText(unittest.TestCase):

    #  The function should correctly split a text into sentences.
    def test_split_sentences(self):
        text = "This is the first sentence. This is the second sentence."
        expected_result = ("This is the first sentence. This is the second sentence.", 0, 2, 0)
        self.assertEqual(process_text(text), expected_result)

    #  The function should capitalize the first letter of each sentence.
    def test_capitalize_sentences(self):
        text = "this is the first sentence. this is the second sentence."
        expected_result = ("This is the first sentence. This is the second sentence.", 0, 0, 0)
        self.assertEqual(process_text(text), expected_result)

    #  The function should count the number of digits in the capitalized text.
    def test_count_digits(self):
        text = "This is a sentence with 3 digits: 1, 2, and 3."
        expected_result = ("This is a sentence with 3 digits: 1, 2, and 3.", 3, 0, 0)
        self.assertEqual(process_text(text), expected_result)

    #  The function should handle an empty string as input.
    def test_empty_string(self):
        text = ""
        expected_result = ("", 0, 0, 0)
        self.assertEqual(process_text(text), expected_result)

    #  The function should handle a string with no sentences.
    def test_no_sentences(self):
        text = "This is not a sentence"
        expected_result = ("This is not a sentence", 0, 0, 0)
        self.assertEqual(process_text(text), expected_result)

    #  The function should handle a string with only one sentence.
    def test_one_sentence(self):
        text = "This is the only sentence."
        expected_result = ("This is the only sentence.", 0, 0, 0)
        self.assertEqual(process_text(text), expected_result)
