
# Generated by CodiumAI

from homework.ex11_14_01 import sum_of_range

import unittest

class TestSumOfRange(unittest.TestCase):

    #  Returns the sum of a range of numbers when given a start and end value
    def test_sum_of_range_positive(self):
        result = sum_of_range(1, 5)
        self.assertEqual(result, 15)

    #  Returns 0 when start and end values are both 0
    def test_sum_of_range_zero(self):
        result = sum_of_range(0, 0)
        self.assertEqual(result, 0)

    #  Returns the start value when start and end values are the same
    def test_sum_of_range_same_value(self):
        result = sum_of_range(3, 3)
        self.assertEqual(result, 3)

    #  Returns None when start value is None
    def test_sum_of_range_start_none(self):
        result = sum_of_range(None, 5)
        self.assertIsNone(result)

    #  Returns None when end value is None
    def test_sum_of_range_end_none(self):
        result = sum_of_range(1, None)
        self.assertIsNone(result)

    #  Returns None when both start and end values are None
    def test_sum_of_range_both_none(self):
        result = sum_of_range(None, None)
        self.assertIsNone(result)
