# Generated by CodiumAI


import unittest

from homework.ex13_14_01 import is_happy_number


class TestIsHappyNumber(unittest.TestCase):

    #  Returns True for a number with equal sum of its first and last three digits
    def test_equal_sum_of_first_and_last_three_digits(self):
        self.assertTrue(is_happy_number(123123))
        self.assertTrue(is_happy_number(456456))
        self.assertTrue(is_happy_number(789789))

    #  Returns False for a number with unequal sum of its first and last three digits
    def test_unequal_sum_of_first_and_last_three_digits(self):
        self.assertFalse(is_happy_number(123456))
        self.assertFalse(is_happy_number(654321))
        self.assertFalse(is_happy_number(987654))

    #  Returns False for a number with less than six digits
    def test_less_than_six_digits(self):
        self.assertFalse(is_happy_number(123))
        self.assertFalse(is_happy_number(456))
        self.assertFalse(is_happy_number(789))

    #  Returns False for a number with more than six digits
    def test_more_than_six_digits(self):
        self.assertFalse(is_happy_number(1234567))
        self.assertFalse(is_happy_number(7654321))
        self.assertFalse(is_happy_number(9876543))

    #  Returns False for a number with non-numeric characters
    def test_non_numeric_characters(self):
        self.assertFalse(is_happy_number("abc123"))
        self.assertFalse(is_happy_number("456def"))
        self.assertFalse(is_happy_number("789ghi"))
