
# Generated by CodiumAI

from homework.ex10_14_01 import max_of_four

import unittest

class TestMaxOfFour(unittest.TestCase):

    #  The function returns the largest number when all inputs are positive integers.
    def test_positive_integers(self):
        result = max_of_four(5, 10, 8, 3)
        self.assertEqual(result, 10)

    #  The function returns the largest negative number when all inputs are negative integers.
    def test_negative_integers(self):
        result = max_of_four(-5, -10, -8, -3)
        self.assertEqual(result, -3)

    #  The function returns the largest number when all inputs are the same positive integer.
    def test_same_positive_integer(self):
        result = max_of_four(5, 5, 5, 5)
        self.assertEqual(result, 5)

    #  The function returns an error message when one or more inputs are not integers.
    def test_non_integer_input(self):
        with self.assertRaises(TypeError):
            max_of_four(5, '10', 8, 3)

    #  The function returns an error message when one or more inputs are None.
    def test_none_input(self):
        with self.assertRaises(TypeError):
            max_of_four(5, 10, None, 3)

    #  The function returns an error message when all inputs are None.
    def test_all_none_input(self):
        with self.assertRaises(TypeError):
            max_of_four(None, None, None, None)
