# Generated by CodiumAI

from HM21_01.ex9 import count_elements

import unittest


class TestCountElements(unittest.TestCase):

    #  The function returns the correct count of even numbers in a list of integers.
    def test_even_count(self):
        # Arrange
        list_of_integers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

        # Act
        even_count, _, _, _ = count_elements(list_of_integers)

        # Assert
        self.assertEqual(even_count, 5)

    #  The function returns the correct count of odd numbers in a list of integers.
    def test_odd_count(self):
        # Arrange
        list_of_integers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

        # Act
        _, odd_count, _, _ = count_elements(list_of_integers)

        # Assert
        self.assertEqual(odd_count, 5)

    #  The function returns the correct count of positive numbers in a list of integers.
    def test_positive_count(self):
        # Arrange
        list_of_integers = [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]

        # Act
        _, _, positive_count, _ = count_elements(list_of_integers)

        # Assert
        self.assertEqual(positive_count, 6)

    #  The function returns the correct counts for an empty list.
    def test_empty_list(self):
        # Arrange
        list_of_integers = []

        # Act
        even_count, odd_count, positive_count, negative_count = count_elements(list_of_integers)

        # Assert
        self.assertEqual(even_count, 0)
        self.assertEqual(odd_count, 0)
        self.assertEqual(positive_count, 0)
        self.assertEqual(negative_count, 0)

    #  The function returns the correct counts for a list with only one even number.
    def test_one_even_number(self):
        # Arrange
        list_of_integers = [2]

        # Act
        even_count, odd_count, positive_count, negative_count = count_elements(list_of_integers)

        # Assert
        self.assertEqual(even_count, 1)
        self.assertEqual(odd_count, 0)
        self.assertEqual(positive_count, 1)
        self.assertEqual(negative_count, 0)

    #  The function returns the correct counts for a list with only one odd number.
    def test_one_odd_number(self):
        # Arrange
        list_of_integers = [3]

        # Act
        even_count, odd_count, positive_count, negative_count = count_elements(list_of_integers)

        # Assert
        self.assertEqual(even_count, 0)
        self.assertEqual(odd_count, 1)
        self.assertEqual(positive_count, 1)
        self.assertEqual(negative_count, 0)
